### ISSUE TITLE
Can't find lbs

### ISSUE THREAD

**Issue by duolinwang** [labstructbioinf/DeepCoil_Paper_2018#1]
Hi, 

I cannot find the lbs folder, do you forget to upload it?  

Thank you!

Duolin

**Comment by labstructbioinf** [comment]
Hello Duolin, 

lbs is available as a separate repository at https://github.com/labstructbioinf/lbs-tools

Best wishes,
lbs team

**Comment by duolinwang** [comment]
Thanks!
